---
repos:
  - repo: https://github.com/python/black
    rev: 21.7b0
    hooks:
      - id: black
        language_version: python3
        args: [--line-length=100]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: debug-statements
      - id: check-yaml
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://opendev.org/openstack/bashate.git
    rev: 2.0.0
    hooks:
      - id: bashate
        args: [-v, --max-line-length, '100']
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.26.2
    hooks:
      - id: yamllint
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-black
  - repo: https://github.com/PyCQA/isort
    rev: 5.9.3
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]

exclude: bubctl/pydfu\.py
