---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: debug-statements
      - id: check-yaml
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://opendev.org/openstack/bashate.git
    rev: 2.0.0
    hooks:
      - id: bashate
        args: [--max-line-length, '100']
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.26.2
    hooks:
      - id: yamllint
